### ISSUE TITLE
Epic - validation rules  (Art. 7)

### ISSUE THREAD

**Issue by nico4** [eaudeweb/ozone#440]
## Imports/Exports  (related with #81)

- [ ] 1. For rows which have one country selected, either one of these three fields must exist: _quantity_total_new_ , _quantity_total_recovered_, _quantity_polyols_. 
Error message: _Total quantity imported for all uses is required._

- [ ] 2. For rows which have one country selected, sum(feedstock + total exempted + QPS for annex E) must be <= sum(total_new + total_recovered). Value total exempted = essential uses + critical uses + ... + other uses (except polyols). 
Error message: _Total quantity imported (respectiv exported) for all uses must be higher than the sum of individual components._

- [x] 3. When there are rows without any country, one extra validation is needed when party adds several rows for the same substance, some with country, one without any country, for instance party reports ExpNew and ExpRecov for each country, but the ExpFeedstock alltogether (see existing submission for China/2016/exports of HCFC-22). The submission will therefore contain:
    - one row for each country with some non-zero "total quantity exported for all uses" and zero feedstock
    - one more row with zero "total quantity" but non-zero feedstock

    For rows which don't have a country the previous rule (total quantity >= sum of all components except polyol) does not apply anymore at row level. But at substance/blend level, the feedstock, essential, critical, etc. sum of exempted quantities (+qps for Annex E) should still be lower than the sum of total quantities (new+recovered) for the corresponding substance/blend . Quantity_polyols are always excluded. 

## Production (related with #373)
- [ ] 4a. Column (3) should not be empty (total production for all uses / captured for all uses for FII)
- [ ] 4b. Total production (3) must be higher than feedstock (4) + exempted (5) + Art5 (7) + QPS for Annex E
- [ ] 4c. For annex F2, captured for all uses (3) should be >= (4a) + (4b) + (5)

## Destruction (related with #212)

- [ ] 5. The quantity destroyed field is the only mandatory field.

## Emissions (related with  #212)

- [ ] 6. Facility name (column 1) and generated emissions (column 6) are mandatory
- [ ] 7. If either one of columns 3a, 3b, 3c is filled in, then 3a must be >= 3b + 3c
- [ ] 8. if there are values in all these fields (2, 3a, 4, 5, 6) then 2 must be equal to 3a+4+5+6
- [ ] 9. if not all of (2, 3a, 4, 5, 6) have values, then 2 must be >= to 3a+4+5+6

## Non-party (related with  #212)

- [ ] 10. Either one of 4, 5, 6, 7 should be filled in

**Comment by mihai-macaneata** [comment]
11. NB: column 3 is optional 
 5. Please see why the comments (OS and party) are missing from this tab
are not validations


 3. When there are rows without any country, one extra validation....
Will only be/Is implemented  in backend

Production tab validations are missing ( https://github.com/eaudeweb/ozone/issues/373 )

**Comment by sorinstelian** [comment]
Ticking checkbox 3, as it has been implemented in the backend.
