### ISSUE TITLE
EPIC - Register a  Party

### ISSUE THREAD

**Issue by nico4** [eaudeweb/ozone#531]
- [x] As a Secretariat, using the Django Administration I create an account for the Party.
- [x] The System sends an email to Party containing the activation link.
- [x] As a Party, I follow the email instructions, which redirects me to a System page where I'm choosing the system language and the password.
- [x] The System sends a confirmation email to the Party, with instructions on how to use the System.
- [x] The System sends a confirmation email to the Secretariat, confirming that the Party has successfully registered in the System.

**Comment by alexkiro** [comment]
> * [x] As a Secretariat, using the Django Administration I create an account for the Party.
> * [x]  The System sends an email to Party containing the activation link.

FWIW, these two are already done
